name: Publish to Pypi

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    push_to_pypi:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
# TODO disabling `lfs` due to service rate limits (for now)
#              with:
#                  lfs: 'true'
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: "Installs dependencies"
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install pooch setuptools wheel twine
                  (echo "import pooch" ; \
                   echo "url = 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx'"; \
                   echo "md5 = '60024c5c889badc19c04ad937298a77b'"; \
                   echo "fname = url.rsplit('/', 1)[1]"; \
                   echo "pooch.retrieve(url, f'md5:{md5}', fname=fname, path='./rembg')") \
                  | python
                  chmod 777 ./rembg/*.onnx

            - name: "Builds and uploads to PyPI"
              run: |
                  python3 setup.py sdist bdist_wheel
                  python3 -m twine upload dist/*
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
